version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres_test_work
    restart: always
    environment:
      POSTGRES_DB: testwork
      POSTGRES_USER: usertest
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

